### ISSUE TITLE
Apparent Lock contention in Downloader

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout-apm-php#119] opened 2019-11-26 18:11 UTC
Customer reported an issue around downloading, or perhaps around higher throughput environments causing lock contention.

---

We had quite a few of these errors:
Could not obtain download lock on /tmp/scout_apm_core/scout_apm_core-v1.2.4-x86_64-unknown-linux-gnu/download.lock: ErrorException: fopen(/tmp/scout_apm_core/scout_apm_core-v1.2.4-x86_64-unknown-linux-gnu/download.lock): failed to open stream: File exists in /app/vendor/scoutapp/scout-apm-php/src/CoreAgent/Downloader.php:136

 2019/11/25 11:17:29 [error] 215#0: *2442 connect() to unix:/tmp/heroku.fcgi.9303.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client: <snip>, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/tmp/heroku.fcgi.9303.sock:", host: "myapp.herokuapp.com"

**Comment by asgrim** [comment] 2019-11-27 08:51
Is this not by design to prevent multiple processes trying to download the core agent concurrently?

This process: we call `cleanStaleDownloadLock` which checks to see if the file was created more than 2 mins ago; if it wasn't, it removes it. Clearly it didn't remove it, so we fail to obtain the lock, so don't proceed to download;

My assumption is that in another process, the download lock has been set successfully, the core agent downloaded, and eventually the lock removed?

Are we seeing the download happening at all anywhere, or are all processes failing?

Another thought I had: `time()` vs `filectime()` may be different? In this instance, perhaps an alternative approach (e.g. using `flock` to acquire a lock on a file) may work better?

**Comment by cschneid** [comment] 2019-11-27 18:24
This could be as simple as a too-noisy log message. 

But I'd assume that we don't attempt to download/lock at all once the core agent has started? The sequence should be attempt to connect, if failed, attempt to launch, if failed, attempt to download then launch.

**Comment by asgrim** [comment] 2019-12-03 11:02
Taking a look at `\Scoutapm\CoreAgent\AutomaticDownloadAndLaunchManager::launch` the sequence is:

 - Try to connect (in `\Scoutapm\Connector\SocketConnector::__construct`) and ignore failures
 - In `\Scoutapm\Agent::connect`, if not already connected, call `launch()`, which
    - Verifies (i.e. tries to read manifest and check the hash matches)
    - If not verified, download
    - Verifies again - if fails now, we exit
    - If verified, launch

**Comment by asgrim** [comment] 2019-12-03 11:05
I think the question to help diagnose this: does the core agent eventually start and the log messages stop?

**Comment by chabior** [comment] 2019-12-03 11:07
Like @cschneid said the message was just a debug message. The agent started, but the performance was so low that most of the requests reached 30s timeout.

**Comment by lchachurski** [comment] 2019-12-03 14:06
Adding a bit of context

Heroku screenshot
<img width="371" alt="Zrzut ekranu 2019-12-3 o 13 43 38" src="https://user-images.githubusercontent.com/3366227/70058010-6df64300-15de-11ea-8850-dfbe90f415c8.png">


Scoutapp screenshot
<img width="1429" alt="Zrzut ekranu 2019-12-3 o 13 44 18" src="https://user-images.githubusercontent.com/3366227/70057993-68006200-15de-11ea-9fdd-77e3ae8f732d.png">


Heroku logs:
```
2019-12-03T12:40:30.511220+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] SendRequestToScout succeeded
2019-12-03T12:40:30.511290+00:00 app[web.1]:
2019-12-03T12:40:30.511573+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] SendRequestToScout succeeded
2019-12-03T12:40:30.511647+00:00 app[web.1]:
2019-12-03T12:40:30.511931+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] SendRequestToScout succeeded
2019-12-03T12:40:30.511986+00:00 app[web.1]:
2019-12-03T12:40:30.512419+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] SendRequestToScout succeeded
2019-12-03T12:40:30.512443+00:00 app[web.1]:
2019-12-03T12:40:30.521056+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] Agent is starting
2019-12-03T12:40:30.521084+00:00 app[web.1]:
2019-12-03T12:40:30.523151+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] Scout Core Agent Connected
2019-12-03T12:40:30.523205+00:00 app[web.1]:
2019-12-03T12:40:30.523427+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] Handle MiddlewareInstrument
2019-12-03T12:40:30.523490+00:00 app[web.1]:
2019-12-03T12:40:30.523733+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] Handle ActionInstrument
2019-12-03T12:40:30.523937+00:00 app[web.1]:
2019-12-03T12:40:30.524480+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] Agent is starting
2019-12-03T12:40:30.524506+00:00 app[web.1]:
2019-12-03T12:40:30.525454+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] Agent is starting
2019-12-03T12:40:30.525456+00:00 app[web.1]:
2019-12-03T12:40:30.526088+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] Agent is starting
2019-12-03T12:40:30.526091+00:00 app[web.1]:
2019-12-03T12:40:30.526838+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] Scout Core Agent Connected
2019-12-03T12:40:30.526879+00:00 app[web.1]:
2019-12-03T12:40:30.527087+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] Handle MiddlewareInstrument
2019-12-03T12:40:30.527089+00:00 app[web.1]:
2019-12-03T12:40:30.527473+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] Handle ActionInstrument
2019-12-03T12:40:30.527500+00:00 app[web.1]:
2019-12-03T12:40:30.528839+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] Scout Core Agent Connected
2019-12-03T12:40:30.528841+00:00 app[web.1]:
2019-12-03T12:40:30.529003+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] Handle MiddlewareInstrument
2019-12-03T12:40:30.529005+00:00 app[web.1]:
2019-12-03T12:40:30.529535+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] Handle ActionInstrument
2019-12-03T12:40:30.529536+00:00 app[web.1]:
2019-12-03T12:40:30.530325+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] Scout Core Agent Connected
2019-12-03T12:40:30.530327+00:00 app[web.1]:
2019-12-03T12:40:30.530545+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] Handle MiddlewareInstrument
2019-12-03T12:40:30.530547+00:00 app[web.1]:
2019-12-03T12:40:30.531176+00:00 app[web.1]: [03-Dec-2019 12:40:30 UTC] [2019-12-03 12:40:30] production.DEBUG: [Scout] Handle ActionInstrument
2019-12-03T12:40:30.531178+00:00 app[web.1]:

# some 499 htto errors
2019-12-03T12:40:31.150516+00:00 app[web.1]: 11.11.11.11 - - [03/Dec/2019:12:40:31 +0000] "GET /some-url HTTP/1.1" 499 0 "referrer  url" "browser os etc"

#some request timeout errors
2019-12-03T12:40:31.148783+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/some-url" host=app.herokuapp.com request_id=randomhash fwd="ip addresses" dyno=web.1 connect=0ms service=30001ms status=503 bytes=0 protocol=https

# some fcgi socket errors together with some 502 bad gateway errors
2019-12-03T12:40:31.532481+00:00 app[web.1]: 2019/12/03 12:40:31 [error] 213#0: *6358 connect() to unix:/tmp/heroku.fcgi.48882.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client: 11.11.11.11, server: localhost, request: "GET /some-url HTTP/1.1", upstream: "fastcgi://unix:/tmp/heroku.fcgi.48882.sock:", host: "app.herokuapp.com"
2019-12-03T12:40:31.532918+00:00 app[web.1]: 11.11.11.11 - - [03/Dec/2019:12:40:31 +0000] "GET /some-url HTTP/1.1" 502 150 "-" "node-superagent/3.8.3
2019-12-03T12:40:31.551678+00:00 app[web.1]: 2019/12/03 12:40:31 [error] 213#0: *6360 connect() to unix:/tmp/heroku.fcgi.48882.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client: 11.11.11.11, server: localhost, request: "GET /some-url HTTP/1.1", upstream: "fastcgi://unix:/tmp/heroku.fcgi.48882.sock:", host: "app.herokuapp.com", referrer: "/some-url"
2019-12-03T12:40:31.552516+00:00 app[web.1]: 11.11.11.11 - - [03/Dec/2019:12:40:31 +0000] "GET /some-url HTTP/1.1" 502 552 "https://domain/url" "browser info"


2019-12-03T12:40:33.469875+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] SendRequestToScout succeeded
2019-12-03T12:40:33.469888+00:00 app[web.1]:
2019-12-03T12:40:33.470071+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] SendRequestToScout succeeded
2019-12-03T12:40:33.470073+00:00 app[web.1]:
2019-12-03T12:40:33.470285+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] SendRequestToScout succeeded
2019-12-03T12:40:33.470287+00:00 app[web.1]:
2019-12-03T12:40:33.470500+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] SendRequestToScout succeeded
2019-12-03T12:40:33.470529+00:00 app[web.1]:
2019-12-03T12:40:33.487919+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] Agent is starting
2019-12-03T12:40:33.487966+00:00 app[web.1]:
2019-12-03T12:40:33.488235+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] Agent is starting
2019-12-03T12:40:33.488278+00:00 app[web.1]:
2019-12-03T12:40:33.488556+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] Scout Core Agent Connected
2019-12-03T12:40:33.488558+00:00 app[web.1]:
2019-12-03T12:40:33.488787+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] Handle MiddlewareInstrument
2019-12-03T12:40:33.488800+00:00 app[web.1]:
2019-12-03T12:40:33.488994+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] Scout Core Agent Connected
2019-12-03T12:40:33.488996+00:00 app[web.1]:
2019-12-03T12:40:33.489191+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] Handle MiddlewareInstrument
2019-12-03T12:40:33.489192+00:00 app[web.1]:
2019-12-03T12:40:33.489388+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] Handle ActionInstrument
2019-12-03T12:40:33.489390+00:00 app[web.1]:
2019-12-03T12:40:33.489578+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] Handle ActionInstrument
2019-12-03T12:40:33.489580+00:00 app[web.1]:
2019-12-03T12:40:33.489764+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] Agent is starting
2019-12-03T12:40:33.489767+00:00 app[web.1]:
2019-12-03T12:40:33.491787+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] Agent is starting
2019-12-03T12:40:33.491789+00:00 app[web.1]:
2019-12-03T12:40:33.492003+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] Scout Core Agent Connected
2019-12-03T12:40:33.492005+00:00 app[web.1]:
2019-12-03T12:40:33.492210+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] Handle MiddlewareInstrument
2019-12-03T12:40:33.492237+00:00 app[web.1]:
2019-12-03T12:40:33.492581+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] Handle ActionInstrument
2019-12-03T12:40:33.492583+00:00 app[web.1]:
2019-12-03T12:40:33.495162+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] Scout Core Agent Connected
2019-12-03T12:40:33.495190+00:00 app[web.1]:
2019-12-03T12:40:33.495411+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] Handle MiddlewareInstrument
2019-12-03T12:40:33.495442+00:00 app[web.1]:
2019-12-03T12:40:33.495811+00:00 app[web.1]: [03-Dec-2019 12:40:33 UTC] [2019-12-03 12:40:33] production.DEBUG: [Scout] Handle ActionInstrument
2019-12-03T12:40:33.495839+00:00 app[web.1]:


# some 499 htto errors
2019-12-03T12:40:34.150516+00:00 app[web.1]: 11.11.11.11 - - [03/Dec/2019:12:40:31 +0000] "GET /some-url HTTP/1.1" 499 0 "referrer  url" "browser os etc"

#some request timeout errors
2019-12-03T12:40:34.148783+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/some-url" host=app.herokuapp.com request_id=randomhash fwd="ip addresses" dyno=web.1 connect=0ms service=30001ms status=503 bytes=0 protocol=https

# some fcgi socket errors together with some 502 bad gateway errors
2019-12-03T12:40:34.532481+00:00 app[web.1]: 2019/12/03 12:40:31 [error] 213#0: *6358 connect() to unix:/tmp/heroku.fcgi.48882.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client: 11.11.11.11, server: localhost, request: "GET /some-url HTTP/1.1", upstream: "fastcgi://unix:/tmp/heroku.fcgi.48882.sock:", host: "app.herokuapp.com"
2019-12-03T12:40:34.532918+00:00 app[web.1]: 11.11.11.11 - - [03/Dec/2019:12:40:31 +0000] "GET /some-url HTTP/1.1" 502 150 "-" "node-superagent/3.8.3
2019-12-03T12:40:34.551678+00:00 app[web.1]: 2019/12/03 12:40:31 [error] 213#0: *6360 connect() to unix:/tmp/heroku.fcgi.48882.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client: 11.11.11.11, server: localhost, request: "GET /some-url HTTP/1.1", upstream: "fastcgi://unix:/tmp/heroku.fcgi.48882.sock:", host: "app.herokuapp.com", referrer: "/some-url"
2019-12-03T12:40:34.552516+00:00 app[web.1]: 11.11.11.11 - - [03/Dec/2019:12:40:31 +0000] "GET /some-url HTTP/1.1" 502 552 "https://domain/url" "browser info"


2019-12-03T12:40:36.420367+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] SendRequestToScout succeeded
2019-12-03T12:40:36.420438+00:00 app[web.1]:
2019-12-03T12:40:36.420666+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] SendRequestToScout succeeded
2019-12-03T12:40:36.420689+00:00 app[web.1]:
2019-12-03T12:40:36.421662+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] SendRequestToScout succeeded
2019-12-03T12:40:36.421692+00:00 app[web.1]:
2019-12-03T12:40:36.430438+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] Agent is starting
2019-12-03T12:40:36.430467+00:00 app[web.1]:
2019-12-03T12:40:36.432958+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] Scout Core Agent Connected
2019-12-03T12:40:36.432984+00:00 app[web.1]:
2019-12-03T12:40:36.433202+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] Handle MiddlewareInstrument
2019-12-03T12:40:36.433282+00:00 app[web.1]:
2019-12-03T12:40:36.433666+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] Handle ActionInstrument
2019-12-03T12:40:36.433693+00:00 app[web.1]:
2019-12-03T12:40:36.434505+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] Agent is starting
2019-12-03T12:40:36.434531+00:00 app[web.1]:
2019-12-03T12:40:36.435286+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] Agent is starting
2019-12-03T12:40:36.435288+00:00 app[web.1]:
2019-12-03T12:40:36.437870+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] Scout Core Agent Connected
2019-12-03T12:40:36.437872+00:00 app[web.1]:
2019-12-03T12:40:36.438029+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] Agent is starting
2019-12-03T12:40:36.438031+00:00 app[web.1]:
2019-12-03T12:40:36.438194+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] Handle MiddlewareInstrument
2019-12-03T12:40:36.438196+00:00 app[web.1]:
2019-12-03T12:40:36.438614+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] Handle ActionInstrument
2019-12-03T12:40:36.438642+00:00 app[web.1]:
2019-12-03T12:40:36.439060+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] Scout Core Agent Connected
2019-12-03T12:40:36.439062+00:00 app[web.1]:
2019-12-03T12:40:36.439290+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] Handle MiddlewareInstrument
2019-12-03T12:40:36.439292+00:00 app[web.1]:
2019-12-03T12:40:36.439780+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] Handle ActionInstrument
2019-12-03T12:40:36.439783+00:00 app[web.1]:
2019-12-03T12:40:36.440102+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] Scout Core Agent Connected
2019-12-03T12:40:36.440105+00:00 app[web.1]:
2019-12-03T12:40:36.440371+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] Handle MiddlewareInstrument
2019-12-03T12:40:36.440373+00:00 app[web.1]:
2019-12-03T12:40:36.440938+00:00 app[web.1]: [03-Dec-2019 12:40:36 UTC] [2019-12-03 12:40:36] production.DEBUG: [Scout] Handle ActionInstrument
2019-12-03T12:40:36.440940+00:00 app[web.1]:



# some 499 htto errors
2019-12-03T12:40:38.150516+00:00 app[web.1]: 11.11.11.11 - - [03/Dec/2019:12:40:31 +0000] "GET /some-url HTTP/1.1" 499 0 "referrer  url" "browser os etc"

#some request timeout errors
2019-12-03T12:40:38.148783+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/some-url" host=app.herokuapp.com request_id=randomhash fwd="ip addresses" dyno=web.1 connect=0ms service=30001ms status=503 bytes=0 protocol=https

# some fcgi socket errors together with some 502 bad gateway errors
2019-12-03T12:40:38.532481+00:00 app[web.1]: 2019/12/03 12:40:31 [error] 213#0: *6358 connect() to unix:/tmp/heroku.fcgi.48882.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client: 11.11.11.11, server: localhost, request: "GET /some-url HTTP/1.1", upstream: "fastcgi://unix:/tmp/heroku.fcgi.48882.sock:", host: "app.herokuapp.com"
2019-12-03T12:40:38.532918+00:00 app[web.1]: 11.11.11.11 - - [03/Dec/2019:12:40:31 +0000] "GET /some-url HTTP/1.1" 502 150 "-" "node-superagent/3.8.3
2019-12-03T12:40:38.551678+00:00 app[web.1]: 2019/12/03 12:40:31 [error] 213#0: *6360 connect() to unix:/tmp/heroku.fcgi.48882.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client: 11.11.11.11, server: localhost, request: "GET /some-url HTTP/1.1", upstream: "fastcgi://unix:/tmp/heroku.fcgi.48882.sock:", host: "app.herokuapp.com", referrer: "/some-url"
2019-12-03T12:40:38.552516+00:00 app[web.1]: 11.11.11.11 - - [03/Dec/2019:12:40:31 +0000] "GET /some-url HTTP/1.1" 502 552 "https://domain/url" "browser info"


2019-12-03T12:40:39.343349+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] SendRequestToScout succeeded
2019-12-03T12:40:39.343364+00:00 app[web.1]:
2019-12-03T12:40:39.343509+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] SendRequestToScout succeeded
2019-12-03T12:40:39.343511+00:00 app[web.1]:
2019-12-03T12:40:39.344015+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] SendRequestToScout succeeded
2019-12-03T12:40:39.344042+00:00 app[web.1]:
2019-12-03T12:40:39.344259+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] SendRequestToScout succeeded
2019-12-03T12:40:39.344619+00:00 app[web.1]:
2019-12-03T12:40:39.355872+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] Agent is starting
2019-12-03T12:40:39.355915+00:00 app[web.1]:
2019-12-03T12:40:39.358323+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] Scout Core Agent Connected
2019-12-03T12:40:39.358795+00:00 app[web.1]:
2019-12-03T12:40:39.360047+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] Handle MiddlewareInstrument
2019-12-03T12:40:39.360527+00:00 app[web.1]:
2019-12-03T12:40:39.361778+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] Agent is starting
2019-12-03T12:40:39.362264+00:00 app[web.1]:
2019-12-03T12:40:39.363859+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] Handle ActionInstrument
2019-12-03T12:40:39.366199+00:00 app[web.1]:
2019-12-03T12:40:39.366409+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] Agent is starting
2019-12-03T12:40:39.366411+00:00 app[web.1]:
2019-12-03T12:40:39.366608+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] Scout Core Agent Connected
2019-12-03T12:40:39.366610+00:00 app[web.1]:
2019-12-03T12:40:39.366819+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] Handle MiddlewareInstrument
2019-12-03T12:40:39.366821+00:00 app[web.1]:
2019-12-03T12:40:39.367014+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] Handle ActionInstrument
2019-12-03T12:40:39.367042+00:00 app[web.1]:
2019-12-03T12:40:39.367276+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] Scout Core Agent Connected
2019-12-03T12:40:39.367278+00:00 app[web.1]:
2019-12-03T12:40:39.367484+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] Handle MiddlewareInstrument
2019-12-03T12:40:39.367485+00:00 app[web.1]:
2019-12-03T12:40:39.367713+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] Handle ActionInstrument
2019-12-03T12:40:39.367717+00:00 app[web.1]:
2019-12-03T12:40:39.367904+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] Agent is starting
2019-12-03T12:40:39.367908+00:00 app[web.1]:
2019-12-03T12:40:39.369904+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] Scout Core Agent Connected
2019-12-03T12:40:39.369944+00:00 app[web.1]:
2019-12-03T12:40:39.370154+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] Handle MiddlewareInstrument
2019-12-03T12:40:39.370156+00:00 app[web.1]:
2019-12-03T12:40:39.370567+00:00 app[web.1]: [03-Dec-2019 12:40:39 UTC] [2019-12-03 12:40:39] production.DEBUG: [Scout] Handle ActionInstrument
```

**Comment by asgrim** [comment] 2019-12-03 14:50
I wonder if the PR in scoutapp/scout-apm-php#124 would fix this? Would you be able to give this a try please?

**Comment by asgrim** [comment] 2019-12-04 10:10
#124 has been merged in now, it may be worth retrying with the latest `dev-master` version

**Comment by lchachurski** [comment] 2019-12-07 14:18
It worked (3cbaf12), thanks for the help!

When are you planning to release this one?

**Comment by asgrim** [comment] 2019-12-07 16:50
@lchachurski ah that's good to hear - I'll check if we can do a release on Monday 👍

**Comment by asgrim** [comment] 2019-12-09 17:48
@lchachurski this is now released, please use Composer to update to the latest tag for 2.0.1: https://github.com/scoutapp/scout-apm-php/releases/tag/v2.0.1

Thanks!

**Closed by asgrim** 2019-12-09 17:48 UTC
Labels: bug, question
